# Dog Breed Webscraping

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import os

In [ ]:
# Request information from webpage
page = requests.get('https://www.dogbreedslist.info/all-dog-breeds')
breed_soup = BeautifulSoup(page.content, 'html.parser')

In [ ]:
# Note the error below
breed_soup

<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body>

In [ ]:
# I needed to add headers so the website would think a person was accessing it - otherwise a "Not Acceptable!...This error was
# generated by Mod_Security"
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0',}
page = requests.get('https://www.dogbreedslist.info/all-dog-breeds', headers = headers)
soup = BeautifulSoup(page.content, 'html.parser')

In [ ]:
# View the soup
soup

<!DOCTYPE html>

<html lang="en-US">
<head>
<meta charset="utf-8"/>
<meta content="ie=edge" http-equiv="x-ua-compatible"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>All Dog Breeds - All Types of Dogs (373 Breeds)</title>
<meta content="Browse through our list of dog breeds, and find the best dog for you." name="description">
<link href="https://www.dogbreedslist.info/all-dog-breeds/" rel="canonical"/>
<meta content="en_US" property="og:locale">
<meta content="article" property="og:type">
<meta content="All Dog Breeds - All Types of Dogs (373 Breeds)" property="og:title"/>
<meta content="Browse through our list of dog breeds, and find the best dog for you." property="og:description"/>
<meta content="https://www.dogbreedslist.info/all-dog-breeds/" property="og:url"/>
<meta content="Dogbreedslist.info" property="og:site_name"/>
<meta content="/img/dog-logo-640x427.png" property="og:image"/>
<meta content="/img/dog-logo-640x427.png" property="og:image:secure_url"/>
<link href="/css/dog-v22.css" rel="stylesheet" type="text/css"/>
<link href="/img/favicon.png" rel="icon" sizes="48x48"/>
</meta></meta></meta></head>
<body>
<div class="header">
<div class="wrapper">
<div class="logo">
<div class="dog-logo"><a href="/">Dog Breeds List</a></div>
<div class="cat-logo"><a href="https://www.catbreedslist.com/">Cat Breeds List</a></div>
</div>
<div class="nav">
<a class="home" href="/">Home</a>
<a href="/all-dog-breeds/">All Breeds</a>
<a href="/stories/">Top Stories</a>
</div>
<div class="search"><a href="/search/">Search</a></div>
</div>
</div>
<div class="main">
<div class="main-l">
<input id="toggle" type="checkbox"/>
<label for="toggle"><span class="toggle-button"><i></i><i></i><i></i></span></label>
<div class="toggle-content">
<dl>
<dt>Size</dt>
<dd><a href="/smallest-dog-breeds/">Smallest</a></dd>
<dd><a href="/small-dog-breeds/">Small</a></dd>
<dd><a href="/small-to-medium-dog-breeds/">Small to Medium</a></dd>
<dd><a href="/medium-dog-breeds/">Medium</a></dd>
<dd><a href="/large-dog-breeds/">Large</a></dd>
<dd><a href="/giant-dog-breeds/">Giant</a></dd>
<dt>Characteristics</dt>
<dd><a href="/smartest-dog-breeds/">Smartest</a></dd>
<dd><a href="/hypoallergenic-dog-breeds/">Hypoallergenic</a></dd>
<dd><a href="/fluffy-dog-breeds/">Fluffy</a></dd>
<dd><a href="/guard-dog-breeds/">Best Guard</a></dd>
<dd><a href="/family-dog-breeds/">Best Family</a></dd>
<dd><a href="/best-dog-breeds-for-kids/">Best for Kids</a></dd>
<dd><a href="/low-shedding-dog-breeds/">Low Shedding</a></dd>
<dd><a href="/healthiest-dog-breeds/">Healthiest</a></dd>
<dd><a href="/police-dog-breeds/">Police Dogs</a></dd>
<dd><a href="/calm-dog-breeds/">Most Calm</a></dd>
<dd><a href="/quiet-dog-breeds/">Quietest</a></dd>
<dt>Color</dt>
<dd><a href="/white-dog-breeds/">White</a></dd>
<dd><a href="/black-dog-breeds/">Black</a></dd>
<dd><a href="/grey-dog-breeds/">Grey</a></dd>
<dd><a href="/brown-dog-breeds/">Brown</a></dd>
<dd><a href="/blue-dog-breeds/">Blue</a></dd>
<dd><a href="/red-dog-breeds/">Red</a></dd>
<dt>Coat</dt>
<dd><a href="/hairless-dog-breeds/">Hairless</a></dd>
<dd><a href="/short-haired-dog-breeds/">Short</a></dd>
<dd><a href="/long-haired-dog-breeds/">Long</a></dd>
<dt>Origin</dt>
<dd><a href="/japanese-dog-breeds/">Japan</a></dd>
<dd><a href="/chinese-dog-breeds/">China</a></dd>
<dd><a href="/australian-dog-breeds/">Australia</a></dd>
<dd><a href="/german-dog-breeds/">Germany</a></dd>
<dd><a href="/italian-dog-breeds/">Italy</a></dd>
<dd><a href="/american-dog-breeds/">United States</a></dd>
<dd><a href="/french-dog-breeds/">France</a></dd>
<dt>Group</dt>
<dd><a href="/hound-dog-breeds/">Hound</a></dd>
<dd><a href="/terrier-dog-breeds/">Terrier</a></dd>
<dd><a href="/herding-dog-breeds/">Herding</a></dd>
<dd><a href="/toy-dog-breeds/">Toy</a></dd>
<dd><a href="/working-dog-breeds/">Working</a></dd>
<dd><a href="/sporting-dog-breeds/">Sporting</a></dd>
</dl>
<div class="names-btn"><a href="/cute-puppy-names/">Puppy Names</a></div>
<div class="ask-btn"><a href="/ask-a-vet-online/">Ask a Vet Online</a></div>
</div>
</div>
<div class="main-r">
<div class="a-z">
<a href="/dog-breeds-a-z/">All A-Z</a>
<a href="/start-with-a/">A</a>
<a href="/start-with-b/">B</a>
<a href="/start-with-c/">C</a>
<a href="/start-with-d/">D</a>
<a href="/start-with-e/">E</a>
<a href="/start-with-f/">F</a>
<a href="/start-with-g/">G</a>
<a href="/start-with-h/">H</a>
<a href="/start-with-i/">I</a>
<a href="/start-with-j/">J</a>
<a href="/start-with-k/">K</a>
<a href="/start-with-l/">L</a>
<a href="/start-with-m/">M</a>
<a href="/start-with-n/">N</a>
<a href="/start-with-o/">O</a>
<a href="/start-with-p/">P</a>
<a href="/start-with-r/">R</a>
<a href="/start-with-s/">S</a>
<a href="/start-with-t/">T</a>
<a href="/start-with-v/">V</a>
<a href="/start-with-w/">W</a>
<a href="/start-with-x/">X</a>
<a href="/start-with-y/">Y</a>
</div>
<div class="link-ad1">
<script async="" crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6829205251971804"></script>
<!-- DogBreedsList_LinkAd1 [old] -->
<ins class="adsbygoogle" data-ad-client="ca-pub-6829205251971804" data-ad-format="auto" data-ad-slot="6876588994" data-full-width-responsive="true" style="display:block"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
<div class="title"><h1>All Dog Breeds</h1></div>
<div class="description">Here’s the complete order of rankings, based on AKC’s registration totals during 2020:</div>
<div class="item-w">
<div class="item-1"><p>Dog Breeds</p></div>
<div class="item-2"><p>Popularity<span>2021</span></p></div>
<div class="item-3"><p>Temperament</p></div>
<div class="item-4"><p>Hypoallergenic</p></div>
<div class="item-5"><p>Intelligence</p></div>
</div>
<div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/labrador-retriever.html"><img alt="Labrador Retriever" src="/uploads/dog-pictures/labrador-retriever-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/labrador-retriever.html" title="Labrador Retriever - Price, Temperament, Life span">Labrador Retriever</a></p><span>Lifespan: 10-12 years</span></div><div class="right-c"><div class="pop"><p>#1</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>7</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $800 - $1500</p><span><a href="/all-dog-breeds/labrador-retriever.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#1</p><span>Rank</span></div>
<div class="list-3"><p>Cheerful</p><p>Gentle</p><p>Friendly</p><p>Intelligent</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>7</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/french-bulldog.html"><img alt="French Bulldog" src="/uploads/dog-pictures/french-bulldog-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/french-bulldog.html" title="French Bulldog - Price, Temperament, Life span">French Bulldog</a></p><span>Lifespan: 10-12 years</span></div><div class="right-c"><div class="pop"><p>#2</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>58</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $2000 - $4000</p><span><a href="/all-dog-breeds/french-bulldog.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#2</p><span>Rank</span></div>
<div class="list-3"><p>Playful</p><p>Sociable</p><p>Lively</p><p>Patient</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>58</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/golden-retriever.html"><img alt="Golden Retriever" src="/uploads/dog-pictures/golden-retriever-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/golden-retriever.html" title="Golden Retriever - Price, Temperament, Life span">Golden Retriever</a></p><span>Lifespan: 10-12 years</span></div><div class="right-c"><div class="pop"><p>#3</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>4</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1000 - $2000</p><span><a href="/all-dog-breeds/golden-retriever.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#3</p><span>Rank</span></div>
<div class="list-3"><p>Intelligent</p><p>Kind</p><p>Friendly</p><p>Confident</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>4</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/german-shepherd-dog.html"><img alt="German Shepherd" src="/uploads/dog-pictures/german-shepherd-dog-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/german-shepherd-dog.html" title="German Shepherd Dog - Price, Temperament, Life span">German Shepherd</a></p><span>Lifespan: 10-13 years</span></div><div class="right-c"><div class="pop"><p>#4</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>3</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $800 - $2000</p><span><a href="/all-dog-breeds/german-shepherd-dog.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#4</p><span>Rank</span></div>
<div class="list-3"><p>Courageous</p><p>Intelligent</p><p>Loyal</p><p>Watchful</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>3</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/poodle.html"><img alt="Poodle" src="/uploads/dog-pictures/poodle-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/poodle.html" title="Poodle (Standard) - Price, Temperament, Life span">Poodle</a></p><span>Lifespan: 12-15 years</span></div><div class="right-c"><div class="pop"><p>#5</p><span>Popularity</span></div><div class="hyp"><p class="yes">Yes</p><span>Hypoallergenic</span></div><div class="int"><p>2</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1200 - $2500</p><span><a href="/all-dog-breeds/poodle.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#5</p><span>Rank</span></div>
<div class="list-3"><p>Intelligent</p><p>Faithful</p><p>Trainable</p><p>Instinctual</p><span>...</span></div>
<div class="list-4"><p class="yes">Yes</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>2</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/bulldog.html"><img alt="Bulldog" src="/uploads/dog-pictures/bulldog-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/bulldog.html" title="Bulldog - Price, Temperament, Life span">Bulldog</a></p><span>Lifespan: 8-10 years</span></div><div class="right-c"><div class="pop"><p>#6</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>77</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $2000 - $4000</p><span><a href="/all-dog-breeds/bulldog.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#6</p><span>Rank</span></div>
<div class="list-3"><p>Friendly</p><p>Docile</p><p>Willful</p><p>Gregarious</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>77</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/beagle.html"><img alt="Beagle" src="/uploads/dog-pictures/beagle-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/beagle.html" title="Beagle - Price, Temperament, Life span">Beagle</a></p><span>Lifespan: 12-15 years</span></div><div class="right-c"><div class="pop"><p>#7</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>72</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $800 - $1500</p><span><a href="/all-dog-breeds/beagle.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#7</p><span>Rank</span></div>
<div class="list-3"><p>Gentle</p><p>Intelligent</p><p>Even Tempered</p><p>Determined</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>72</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/rottweiler.html"><img alt="Rottweiler" src="/uploads/dog-pictures/rottweiler-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/rottweiler.html" title="Rottweiler - Price, Temperament, Life span">Rottweiler</a></p><span>Lifespan: 8-11 years</span></div><div class="right-c"><div class="pop"><p>#8</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>9</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1200 - $2000</p><span><a href="/all-dog-breeds/rottweiler.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#8</p><span>Rank</span></div>
<div class="list-3"><p>Intelligent</p><p>Courageous</p><p>Fearless</p><p>Confident</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>9</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/german-shorthaired-pointer.html"><img alt="German Shorthaired Pointer" src="/uploads/dog-pictures/german-shorthaired-pointer-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/german-shorthaired-pointer.html" title="German Shorthaired Pointer - Price, Temperament, Life span">German Shorthaired Pointer</a></p><span>Lifespan: 12-14 years</span></div><div class="right-c"><div class="pop"><p>#9</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>17</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $800 - $1500</p><span><a href="/all-dog-breeds/german-shorthaired-pointer.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#9</p><span>Rank</span></div>
<div class="list-3"><p>Intelligent</p><p>Trainable</p><p>Boisterous</p><p>Cooperative</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>17</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/dachshund.html"><img alt="Dachshund" src="/uploads/dog-pictures/dachshund-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/dachshund.html" title="Dachshund (Toy, Miniature, Standard) - Price, Temperament, Life span">Dachshund</a></p><span>Lifespan: 12-15 years</span></div><div class="right-c"><div class="pop"><p>#10</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>49</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $800 - $1500</p><span><a href="/all-dog-breeds/dachshund.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#10</p><span>Rank</span></div>
<div class="list-3"><p>Clever</p><p>Courageous</p><p>Devoted</p><p>Lively</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>49</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/pembroke-welsh-corgi.html"><img alt="Pembroke Welsh Corgi" src="/uploads/dog-pictures/pembroke-welsh-corgi-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/pembroke-welsh-corgi.html" title="Pembroke Welsh Corgi - Price, Temperament, Life span">Pembroke Welsh Corgi</a></p><span>Lifespan: Purebred years</span></div><div class="right-c"><div class="pop"><p>#11</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>11</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1000 - $2000</p><span><a href="/all-dog-breeds/pembroke-welsh-corgi.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#11</p><span>Rank</span></div>
<div class="list-3"><p>Intelligent</p><p>Playful</p><p>Outgoing</p><p>Friendly</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>11</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/australian-shepherd.html"><img alt="Australian Shepherd" src="/uploads/dog-pictures/australian-shepherd-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/australian-shepherd.html" title="Australian Shepherd - Price, Temperament, Life span">Australian Shepherd</a></p><span>Lifespan: 12-15 years</span></div><div class="right-c"><div class="pop"><p>#12</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>42</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1000 - $2000</p><span><a href="/all-dog-breeds/australian-shepherd.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#12</p><span>Rank</span></div>
<div class="list-3"><p>Active</p><p>Intelligent</p><p>Good-natured</p><p>Protective</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>42</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/yorkshire-terrier.html"><img alt="Yorkshire Terrier" src="/uploads/dog-pictures/yorkshire-terrier-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/yorkshire-terrier.html" title="Yorkshire Terrier - Price, Temperament, Life span">Yorkshire Terrier</a></p><span>Lifespan: 12-16 years</span></div><div class="right-c"><div class="pop"><p>#13</p><span>Popularity</span></div><div class="hyp"><p class="yes">Yes</p><span>Hypoallergenic</span></div><div class="int"><p>27</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1500 - $3000</p><span><a href="/all-dog-breeds/yorkshire-terrier.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#13</p><span>Rank</span></div>
<div class="list-3"><p>Independent</p><p>Intelligent</p><p>Courageous</p><p>Confident</p><span>...</span></div>
<div class="list-4"><p class="yes">Yes</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>27</p><span>Rank</span></div>
</div><div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/boxer.html"><img alt="Boxer" src="/uploads/dog-pictures/boxer-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/boxer.html" title="Boxer - Price, Temperament, Life span">Boxer</a></p><span>Lifespan: 10-12 years</span></div><div class="right-c"><div class="pop"><p>#14</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>48</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1000 - $2000</p><span><a href="/all-dog-breeds/boxer.html">See Details &gt;</a></span></div></div></div>

In [ ]:
# Create list of the div elements
# There should be one element for each dog in the list (expecting 20)
list = soup.findAll('div', attrs = {'class':'list'})
print(len(list))

20

In [ ]:
# View the list
print(list)

[<div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/labrador-retriever.html"><img alt="Labrador Retriever" src="/uploads/dog-pictures/labrador-retriever-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/labrador-retriever.html" title="Labrador Retriever - Price, Temperament, Life span">Labrador Retriever</a></p><span>Lifespan: 10-12 years</span></div><div class="right-c"><div class="pop"><p>#1</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>7</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $800 - $1500</p><span><a href="/all-dog-breeds/labrador-retriever.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#1</p><span>Rank</span></div>
<div class="list-3"><p>Cheerful</p><p>Gentle</p><p>Friendly</p><p>Intelligent</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>7</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/french-bulldog.html"><img alt="French Bulldog" src="/uploads/dog-pictures/french-bulldog-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/french-bulldog.html" title="French Bulldog - Price, Temperament, Life span">French Bulldog</a></p><span>Lifespan: 10-12 years</span></div><div class="right-c"><div class="pop"><p>#2</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>58</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $2000 - $4000</p><span><a href="/all-dog-breeds/french-bulldog.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#2</p><span>Rank</span></div>
<div class="list-3"><p>Playful</p><p>Sociable</p><p>Lively</p><p>Patient</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>58</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/golden-retriever.html"><img alt="Golden Retriever" src="/uploads/dog-pictures/golden-retriever-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/golden-retriever.html" title="Golden Retriever - Price, Temperament, Life span">Golden Retriever</a></p><span>Lifespan: 10-12 years</span></div><div class="right-c"><div class="pop"><p>#3</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>4</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1000 - $2000</p><span><a href="/all-dog-breeds/golden-retriever.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#3</p><span>Rank</span></div>
<div class="list-3"><p>Intelligent</p><p>Kind</p><p>Friendly</p><p>Confident</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>4</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/german-shepherd-dog.html"><img alt="German Shepherd" src="/uploads/dog-pictures/german-shepherd-dog-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/german-shepherd-dog.html" title="German Shepherd Dog - Price, Temperament, Life span">German Shepherd</a></p><span>Lifespan: 10-13 years</span></div><div class="right-c"><div class="pop"><p>#4</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>3</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $800 - $2000</p><span><a href="/all-dog-breeds/german-shepherd-dog.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#4</p><span>Rank</span></div>
<div class="list-3"><p>Courageous</p><p>Intelligent</p><p>Loyal</p><p>Watchful</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>3</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/poodle.html"><img alt="Poodle" src="/uploads/dog-pictures/poodle-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/poodle.html" title="Poodle (Standard) - Price, Temperament, Life span">Poodle</a></p><span>Lifespan: 12-15 years</span></div><div class="right-c"><div class="pop"><p>#5</p><span>Popularity</span></div><div class="hyp"><p class="yes">Yes</p><span>Hypoallergenic</span></div><div class="int"><p>2</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1200 - $2500</p><span><a href="/all-dog-breeds/poodle.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#5</p><span>Rank</span></div>
<div class="list-3"><p>Intelligent</p><p>Faithful</p><p>Trainable</p><p>Instinctual</p><span>...</span></div>
<div class="list-4"><p class="yes">Yes</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>2</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/bulldog.html"><img alt="Bulldog" src="/uploads/dog-pictures/bulldog-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/bulldog.html" title="Bulldog - Price, Temperament, Life span">Bulldog</a></p><span>Lifespan: 8-10 years</span></div><div class="right-c"><div class="pop"><p>#6</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>77</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $2000 - $4000</p><span><a href="/all-dog-breeds/bulldog.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#6</p><span>Rank</span></div>
<div class="list-3"><p>Friendly</p><p>Docile</p><p>Willful</p><p>Gregarious</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>77</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/beagle.html"><img alt="Beagle" src="/uploads/dog-pictures/beagle-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/beagle.html" title="Beagle - Price, Temperament, Life span">Beagle</a></p><span>Lifespan: 12-15 years</span></div><div class="right-c"><div class="pop"><p>#7</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>72</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $800 - $1500</p><span><a href="/all-dog-breeds/beagle.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#7</p><span>Rank</span></div>
<div class="list-3"><p>Gentle</p><p>Intelligent</p><p>Even Tempered</p><p>Determined</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>72</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/rottweiler.html"><img alt="Rottweiler" src="/uploads/dog-pictures/rottweiler-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/rottweiler.html" title="Rottweiler - Price, Temperament, Life span">Rottweiler</a></p><span>Lifespan: 8-11 years</span></div><div class="right-c"><div class="pop"><p>#8</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>9</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1200 - $2000</p><span><a href="/all-dog-breeds/rottweiler.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#8</p><span>Rank</span></div>
<div class="list-3"><p>Intelligent</p><p>Courageous</p><p>Fearless</p><p>Confident</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>9</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/german-shorthaired-pointer.html"><img alt="German Shorthaired Pointer" src="/uploads/dog-pictures/german-shorthaired-pointer-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/german-shorthaired-pointer.html" title="German Shorthaired Pointer - Price, Temperament, Life span">German Shorthaired Pointer</a></p><span>Lifespan: 12-14 years</span></div><div class="right-c"><div class="pop"><p>#9</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>17</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $800 - $1500</p><span><a href="/all-dog-breeds/german-shorthaired-pointer.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#9</p><span>Rank</span></div>
<div class="list-3"><p>Intelligent</p><p>Trainable</p><p>Boisterous</p><p>Cooperative</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>17</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/dachshund.html"><img alt="Dachshund" src="/uploads/dog-pictures/dachshund-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/dachshund.html" title="Dachshund (Toy, Miniature, Standard) - Price, Temperament, Life span">Dachshund</a></p><span>Lifespan: 12-15 years</span></div><div class="right-c"><div class="pop"><p>#10</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>49</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $800 - $1500</p><span><a href="/all-dog-breeds/dachshund.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#10</p><span>Rank</span></div>
<div class="list-3"><p>Clever</p><p>Courageous</p><p>Devoted</p><p>Lively</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>49</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/pembroke-welsh-corgi.html"><img alt="Pembroke Welsh Corgi" src="/uploads/dog-pictures/pembroke-welsh-corgi-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/pembroke-welsh-corgi.html" title="Pembroke Welsh Corgi - Price, Temperament, Life span">Pembroke Welsh Corgi</a></p><span>Lifespan: Purebred years</span></div><div class="right-c"><div class="pop"><p>#11</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>11</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1000 - $2000</p><span><a href="/all-dog-breeds/pembroke-welsh-corgi.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#11</p><span>Rank</span></div>
<div class="list-3"><p>Intelligent</p><p>Playful</p><p>Outgoing</p><p>Friendly</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>11</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/australian-shepherd.html"><img alt="Australian Shepherd" src="/uploads/dog-pictures/australian-shepherd-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/australian-shepherd.html" title="Australian Shepherd - Price, Temperament, Life span">Australian Shepherd</a></p><span>Lifespan: 12-15 years</span></div><div class="right-c"><div class="pop"><p>#12</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>42</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1000 - $2000</p><span><a href="/all-dog-breeds/australian-shepherd.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#12</p><span>Rank</span></div>
<div class="list-3"><p>Active</p><p>Intelligent</p><p>Good-natured</p><p>Protective</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>42</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/yorkshire-terrier.html"><img alt="Yorkshire Terrier" src="/uploads/dog-pictures/yorkshire-terrier-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/yorkshire-terrier.html" title="Yorkshire Terrier - Price, Temperament, Life span">Yorkshire Terrier</a></p><span>Lifespan: 12-16 years</span></div><div class="right-c"><div class="pop"><p>#13</p><span>Popularity</span></div><div class="hyp"><p class="yes">Yes</p><span>Hypoallergenic</span></div><div class="int"><p>27</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1500 - $3000</p><span><a href="/all-dog-breeds/yorkshire-terrier.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#13</p><span>Rank</span></div>
<div class="list-3"><p>Independent</p><p>Intelligent</p><p>Courageous</p><p>Confident</p><span>...</span></div>
<div class="list-4"><p class="yes">Yes</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>27</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/boxer.html"><img alt="Boxer" src="/uploads/dog-pictures/boxer-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/boxer.html" title="Boxer - Price, Temperament, Life span">Boxer</a></p><span>Lifespan: 10-12 years</span></div><div class="right-c"><div class="pop"><p>#14</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>48</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1000 - $2000</p><span><a href="/all-dog-breeds/boxer.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#14</p><span>Rank</span></div>
<div class="list-3"><p>Playful</p><p>Friendly</p><p>Devoted</p><p>Loyal</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>48</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/cavalier-king-charles-spaniel.html"><img alt="Cavalier King Charles Spaniel" src="/uploads/dog-pictures/cavalier-king-charles-spaniel-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/cavalier-king-charles-spaniel.html" title="Cavalier King Charles Spaniel - Price, Temperament, Life span">Cavalier King Charles Spaniel</a></p><span>Lifespan: 10-14 years</span></div><div class="right-c"><div class="pop"><p>#15</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>44</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1500 - $2500</p><span><a href="/all-dog-breeds/cavalier-king-charles-spaniel.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#15</p><span>Rank</span></div>
<div class="list-3"><p>Playful</p><p>Sociable</p><p>Patient</p><p>Fearless</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>44</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/doberman-pinscher.html"><img alt="Doberman Pinscher" src="/uploads/dog-pictures/doberman-pinscher-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/doberman-pinscher.html" title="Doberman Pinscher - Price, Temperament, Life span">Doberman Pinscher</a></p><span>Lifespan: 10-12 years</span></div><div class="right-c"><div class="pop"><p>#16</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>5</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1200 - $2500</p><span><a href="/all-dog-breeds/doberman-pinscher.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#16</p><span>Rank</span></div>
<div class="list-3"><p>Intelligent</p><p>Obedient</p><p>Loyal</p><p>Energetic</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>5</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/great-dane.html"><img alt="Great Dane" src="/uploads/dog-pictures/great-dane-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/great-dane.html" title="Great Dane - Price, Temperament, Life span">Great Dane</a></p><span>Lifespan: 7-10 years</span></div><div class="right-c"><div class="pop"><p>#17</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>48</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1000 - $2000</p><span><a href="/all-dog-breeds/great-dane.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#17</p><span>Rank</span></div>
<div class="list-3"><p>Gentle</p><p>Friendly</p><p>Devoted</p><p>Reserved</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>48</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/miniature-schnauzer.html"><img alt="Miniature Schnauzer" src="/uploads/dog-pictures/miniature-schnauzer-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/miniature-schnauzer.html" title="Miniature Schnauzer - Price, Temperament, Life span">Miniature Schnauzer</a></p><span>Lifespan: 12-14 years</span></div><div class="right-c"><div class="pop"><p>#18</p><span>Popularity</span></div><div class="hyp"><p class="yes">Yes</p><span>Hypoallergenic</span></div><div class="int"><p>12</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $1200 - $2500</p><span><a href="/all-dog-breeds/miniature-schnauzer.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#18</p><span>Rank</span></div>
<div class="list-3"><p>Intelligent</p><p>Friendly</p><p>Obedient</p><p>Fearless</p><span>...</span></div>
<div class="list-4"><p class="yes">Yes</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>12</p><span>Rank</span></div>
</div>, <div class="list">
<div class="list-1"><div class="left"><a href="/all-dog-breeds/siberian-husky.html"><img alt="Siberian Husky" src="/uploads/dog-pictures/siberian-husky-1.jpg"/></a></div><div class="right"><div class="right-t"><p><a href="/all-dog-breeds/siberian-husky.html" title="Siberian Husky - Price, Temperament, Life span">Siberian Husky</a></p><span>Lifespan: 12-14 years</span></div><div class="right-c"><div class="pop"><p>#19</p><span>Popularity</span></div><div class="hyp"><p>No</p><span>Hypoallergenic</span></div><div class="int"><p>45</p><span>Intelligence</span></div></div><div class="right-b"><p><b>Prices:</b> $600 - $1300</p><span><a href="/all-dog-breeds/siberian-husky.html">See Details &gt;</a></span></div></div></div>
<div class="list-2"><p>#19</p><span>Rank</span></div>
<div class="list-3"><p>Gentle</p><p>Intelligent</p><p>Outgoing</p><p>Friendly</p><span>...</span></div>
<div class="list-4"><p>No</p><span>Hypoallergenic</span></div>
<div class="list-5"><p>45</p><span>Rank</span></div>
</div>, <div class="list">

In [ ]:
# Go through the soup and select the 'div' elements, based on the class 'list_1', which based on above, contains the info we want
breeds = soup.findAll('div', attrs = {'class': 'list-1'}, limit = None)
data = [[x.text for x in y.findAll('p')] for y in breeds]
# Create a dataframe
df = pd.DataFrame(data)

In [ ]:
# Draw the information from the rest of the pages on the website (there are five pages of results)
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0',}
page = requests.get('https://www.dogbreedslist.info/all-dog-breeds/page-2.html', headers = headers)
soup_2 = BeautifulSoup(page.content, 'html.parser')

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0',}
page = requests.get('https://www.dogbreedslist.info/all-dog-breeds/page-3.html', headers = headers)
soup_3 = BeautifulSoup(page.content, 'html.parser')

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0',}
page = requests.get('https://www.dogbreedslist.info/all-dog-breeds/page-4.html', headers = headers)
soup_4 = BeautifulSoup(page.content, 'html.parser')

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0',}
page = requests.get('https://www.dogbreedslist.info/all-dog-breeds/page-5.html', headers = headers)
soup_5 = BeautifulSoup(page.content, 'html.parser')

In [ ]:
# Create lists from each of those pages and check the length (each should be 20)
list_2 = soup_2.findAll('div', attrs = {'class':'list'})
print(len(list))

list_3 = soup_3.findAll('div', attrs = {'class':'list'})
print(len(list))

list_4 = soup_4.findAll('div', attrs = {'class':'list'})
print(len(list))

list_5 = soup_5.findAll('div', attrs = {'class':'list'})
print(len(list))

20
20
20
20

In [ ]:
# Create dataframes from each of the lists
breeds_2 = soup_2.findAll('div', attrs = {'class': 'list-1'}, limit = None)
data_2 = [[x.text for x in y.findAll('p')] for y in breeds]

df_2 = pd.DataFrame(data_2)

breeds = soup_3.findAll('div', attrs = {'class': 'list-1'}, limit = None)
data_3 = [[x.text for x in y.findAll('p')] for y in breeds]

df_3 = pd.DataFrame(data_3)

breeds = soup_4.findAll('div', attrs = {'class': 'list-1'}, limit = None)
data_4 = [[x.text for x in y.findAll('p')] for y in breeds]

df_4 = pd.DataFrame(data_4)

breeds = soup_5.findAll('div', attrs = {'class': 'list-1'}, limit = None)
data_5 = [[x.text for x in y.findAll('p')] for y in breeds]

df_5 = pd.DataFrame(data_5)

In [ ]:
# Append the new dataframes to the end of the original dataframe
df = df.append(df_2)
df = df.append(df_3)
df = df.append(df_4)
df = df.append(df_5)

In [ ]:
df

                     0     1    2   3                      4
0   Labrador Retriever    #1   No   7   Prices: $800 - $1500
1       French Bulldog    #2   No  58  Prices: $2000 - $4000
2     Golden Retriever    #3   No   4  Prices: $1000 - $2000
3      German Shepherd    #4   No   3   Prices: $800 - $2000
4               Poodle    #5  Yes   2  Prices: $1200 - $2500
..                 ...   ...  ...  ..                    ...
15  Standard Schnauzer   #96  Yes  18  Prices: $1500 - $2500
16    Brussels Griffon   #97  Yes   -  Prices: $1800 - $2800
17      English Setter   #98   No  37  Prices: $1000 - $1500
18    Wire Fox Terrier   #99  Yes  51  Prices: $1500 - $3000
19  Norwegian Elkhound  #100   No  36   Prices: $700 - $1500

[100 rows x 5 columns]

In [ ]:
# Change the column names to be descriptive and easy to use in future code
df.rename({0: 'breed_name', 1: 'popularity_rank', 2:'hypoallergenic', 3:'intelligence_rank', 4:'price_range'}, axis = 1, inplace = True)

In [ ]:
df

,breed_name,popularity_rank,hypoallergenic,intelligence_rank,price_range
0,Labrador Retriever,#1,No,7,Prices: $800 - $1500
1,French Bulldog,#2,No,58,Prices: $2000 - $4000
2,Golden Retriever,#3,No,4,Prices: $1000 - $2000
3,German Shepherd,#4,No,3,Prices: $800 - $2000
4,Poodle,#5,Yes,2,Prices: $1200 - $2500
...,...,...,...,...,...
15,Standard Schnauzer,#96,Yes,18,Prices: $1500 - $2500
16,Brussels Griffon,#97,Yes,-,Prices: $1800 - $2800
17,English Setter,#98,No,37,Prices: $1000 - $1500
18,Wire Fox Terrier,#99,Yes,51,Prices: $1500 - $3000
19,Norwegian Elkhound,#100,No,36,Prices: $700 - $1500

In [ ]:
# Remove the '#' characters from the popularity_rank column
df['popularity_rank'] = df.popularity_rank.str.lstrip('#')

In [ ]:
df

,breed_name,popularity_rank,hypoallergenic,intelligence_rank,price_range
0,Labrador Retriever,1,No,7,Prices: $800 - $1500
1,French Bulldog,2,No,58,Prices: $2000 - $4000
2,Golden Retriever,3,No,4,Prices: $1000 - $2000
3,German Shepherd,4,No,3,Prices: $800 - $2000
4,Poodle,5,Yes,2,Prices: $1200 - $2500
...,...,...,...,...,...
15,Standard Schnauzer,96,Yes,18,Prices: $1500 - $2500
16,Brussels Griffon,97,Yes,-,Prices: $1800 - $2800
17,English Setter,98,No,37,Prices: $1000 - $1500
18,Wire Fox Terrier,99,Yes,51,Prices: $1500 - $3000
19,Norwegian Elkhound,100,No,36,Prices: $700 - $1500

In [ ]:
# Strip the word 'Prices:' from the price_range column
df['price_range'] = df.price_range.str.lstrip(' Prices: ')

In [ ]:
df

,breed_name,popularity_rank,hypoallergenic,intelligence_rank,price_range
0,Labrador Retriever,1,No,7,$800 - $1500
1,French Bulldog,2,No,58,$2000 - $4000
2,Golden Retriever,3,No,4,$1000 - $2000
3,German Shepherd,4,No,3,$800 - $2000
4,Poodle,5,Yes,2,$1200 - $2500
...,...,...,...,...,...
15,Standard Schnauzer,96,Yes,18,$1500 - $2500
16,Brussels Griffon,97,Yes,-,$1800 - $2800
17,English Setter,98,No,37,$1000 - $1500
18,Wire Fox Terrier,99,Yes,51,$1500 - $3000
19,Norwegian Elkhound,100,No,36,$700 - $1500

In [ ]:
# Split the price range column on '-' and create two new columns with each half
df[['min_price','max_price']] = df.price_range.str.split("-",expand=True,)

In [ ]:
df

,breed_name,popularity_rank,hypoallergenic,intelligence_rank,price_range,min_price,max_price
0,Labrador Retriever,1,No,7,$800 - $1500,$800,$1500
1,French Bulldog,2,No,58,$2000 - $4000,$2000,$4000
2,Golden Retriever,3,No,4,$1000 - $2000,$1000,$2000
3,German Shepherd,4,No,3,$800 - $2000,$800,$2000
4,Poodle,5,Yes,2,$1200 - $2500,$1200,$2500
...,...,...,...,...,...,...,...
15,Standard Schnauzer,96,Yes,18,$1500 - $2500,$1500,$2500
16,Brussels Griffon,97,Yes,-,$1800 - $2800,$1800,$2800
17,English Setter,98,No,37,$1000 - $1500,$1000,$1500
18,Wire Fox Terrier,99,Yes,51,$1500 - $3000,$1500,$3000
19,Norwegian Elkhound,100,No,36,$700 - $1500,$700,$1500

In [ ]:
# Remove the '$' characters from the front of min_price and max_price
df['min_price'] = df.min_price.str.lstrip('$')
df['max_price'] = df.max_price.str.lstrip(' $')

In [ ]:
df

,breed_name,popularity_rank,hypoallergenic,intelligence_rank,price_range,min_price,max_price
0,Labrador Retriever,1,No,7,$800 - $1500,800,1500
1,French Bulldog,2,No,58,$2000 - $4000,2000,4000
2,Golden Retriever,3,No,4,$1000 - $2000,1000,2000
3,German Shepherd,4,No,3,$800 - $2000,800,2000
4,Poodle,5,Yes,2,$1200 - $2500,1200,2500
...,...,...,...,...,...,...,...
15,Standard Schnauzer,96,Yes,18,$1500 - $2500,1500,2500
16,Brussels Griffon,97,Yes,-,$1800 - $2800,1800,2800
17,English Setter,98,No,37,$1000 - $1500,1000,1500
18,Wire Fox Terrier,99,Yes,51,$1500 - $3000,1500,3000
19,Norwegian Elkhound,100,No,36,$700 - $1500,700,1500

In [ ]:
# Change data type in min_price and max_price to integers
df['min_price'] = df['min_price'].astype(str).astype(int)
df['max_price'] = df['max_price'].astype(str).astype(int)

In [ ]:
df

,breed_name,popularity_rank,hypoallergenic,intelligence_rank,price_range,min_price,max_price
0,Labrador Retriever,1,No,7,$800 - $1500,800,1500
1,French Bulldog,2,No,58,$2000 - $4000,2000,4000
2,Golden Retriever,3,No,4,$1000 - $2000,1000,2000
3,German Shepherd,4,No,3,$800 - $2000,800,2000
4,Poodle,5,Yes,2,$1200 - $2500,1200,2500
...,...,...,...,...,...,...,...
15,Standard Schnauzer,96,Yes,18,$1500 - $2500,1500,2500
16,Brussels Griffon,97,Yes,-,$1800 - $2800,1800,2800
17,English Setter,98,No,37,$1000 - $1500,1000,1500
18,Wire Fox Terrier,99,Yes,51,$1500 - $3000,1500,3000
19,Norwegian Elkhound,100,No,36,$700 - $1500,700,1500

In [ ]:
df

,breed_name,popularity_rank,hypoallergenic,intelligence_rank,price_range,min_price,max_price
0,Labrador Retriever,1,No,7,$800 - $1500,800,1500
1,French Bulldog,2,No,58,$2000 - $4000,2000,4000
2,Golden Retriever,3,No,4,$1000 - $2000,1000,2000
3,German Shepherd,4,No,3,$800 - $2000,800,2000
4,Poodle,5,Yes,2,$1200 - $2500,1200,2500
...,...,...,...,...,...,...,...
15,Standard Schnauzer,96,Yes,18,$1500 - $2500,1500,2500
16,Brussels Griffon,97,Yes,-,$1800 - $2800,1800,2800
17,English Setter,98,No,37,$1000 - $1500,1000,1500
18,Wire Fox Terrier,99,Yes,51,$1500 - $3000,1500,3000
19,Norwegian Elkhound,100,No,36,$700 - $1500,700,1500

In [ ]:
# create excel writer object
writer = pd.ExcelWriter('breeds_df.xlsx')
# write dataframe to excel
df.to_excel(writer)
# save the excel
writer.save()
print('DataFrame is written successfully to Excel File.')

DataFrame is written successfully to Excel File.